### ISSUE TITLE
Update to support modern JS like Optional Chaining

### ISSUE THREAD

**Issue by YenHub** [Skalman/UglifyJS-online#15]
## Scope

When attempting to minify javascript which contains modern operators, such as Optional Chaining, you are given an error:-

![image](https://user-images.githubusercontent.com/34943338/189326866-747405b5-0b0c-4108-b789-dd07a8bed94b.png)

## Solution

UglifyJS as of [3.13.6](https://github.com/mishoo/UglifyJS/releases/tag/v3.13.6) supports optional chaining

Updating the version we're using here will resolve the issue 😄

**Comment by marcusx2** [comment]
bump. Please update this...

**Comment by Skalman** [comment]
This has been fixed in https://github.com/Skalman/UglifyJS-online/pull/18.
