### ISSUE TITLE
Static property

### ISSUE THREAD

**Issue by ulyssesric** [Skalman/UglifyJS-online#16]
Apparently the latest version failed to handle `static` fields in class.

Try to minify sample codes from [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static):

    class ClassWithStaticMethod {
      static staticProperty = 'someValue';
      static staticMethod() {
        return 'static method has been called.';
      }
      static {
        console.log('Class static initialization block called');
      }
    }

and get the error: "`Parse error: Unexpected token: operator (=)`"

**Comment by Skalman** [comment]
The issue is that we're stuck on an old version. I'll merge a PR updating to the latest version.

**Comment by Skalman** [comment]
This has been fixed in https://github.com/Skalman/UglifyJS-online/pull/18.
